apiVersion: v1
kind: Secret
type: opaque
metadata:
  labels:
    app.kubernetes.io/managed-by: cpln-operator
  name: secret
  namespace: default
  annotations:
    cpln.io/org: {{ .Values.org }}
data:
  encoding: cGxhaW4=
  payload: c2VjcmV0LXZhbHVlLTQ=
